<a href="https://colab.research.google.com/github/Lilian-Wamuhu/Lilian-Wamuhu/blob/main/Numpy_Ex_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#61. Find the nearest value from a given value in an array
x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
2.3630750225964836
2


In [4]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [5]:
#63. Create an array class that has a name attribute 
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [6]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[2. 4. 4. 4. 2. 4. 4. 2. 3. 1.]
[3. 7. 7. 7. 3. 7. 7. 3. 5. 1.]


In [7]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [8]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [9]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

<built-in function sum>
[[42 62 41 55]
 [64 55 65 50]
 [50 44 36 74]]


In [10]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.47004795 0.46906149 0.60593718 0.48919631 0.43850616 0.5674813
 0.45242348 0.58586284 0.52775487 0.3573479 ]


In [11]:
#69. How to get the diagonal of a dot product?
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.59589242, 0.6783311 , 0.61622452, 1.96773869, 1.43641379])

In [12]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [13]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [14]:
#72. How to swap two rows of an array? 
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3,  8) ( 3, 50) ( 8, 50) (11, 35) (11, 63) (11, 74) (11, 88) (16, 38)
 (16, 59) (20, 41) (20, 77) (21, 40) (21, 56) (25, 28) (25, 69) (27, 52)
 (27, 55) (28, 69) (35, 88) (38, 59) (40, 56) (41, 45) (41, 52) (41, 77)
 (43, 68) (43, 92) (45, 52) (52, 55) (63, 74) (68, 92)]


In [16]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [17]:
#75. How to compute averages using a sliding window over an array?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [18]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [19]:
#77. How to negate a boolean, or to change the sign of a float inplace?
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.16835186, -0.31883462, -0.92504291, -0.92401595,  0.31623431,
       -0.64025953,  0.49357104,  0.14701859, -0.94537925, -0.74895142,
        0.4536857 , -0.75512183,  0.63701493,  0.33060298, -0.81293886,
        0.64579866, -0.22403908, -0.28551623,  0.33964521, -0.1645494 ,
        0.13940715,  0.00131978, -0.09183157, -0.10653002, -0.38529398,
        0.62714258, -0.59679374, -0.03769685, -0.65569018,  0.02173719,
        0.12852431, -0.49969883, -0.65584689,  0.64094281,  0.46070882,
        0.45470598, -0.90242275, -0.72321788, -0.25202839,  0.07258052,
       -0.53621396, -0.4333846 ,  0.55030525, -0.81428844,  0.51715146,
       -0.26897273, -0.20938283, -0.14003518,  0.14107768,  0.07871203,
       -0.91621704, -0.47252898,  0.64485627,  0.78915166,  0.45166258,
        0.87252194,  0.86675956, -0.84913994,  0.90100047,  0.69762704,
       -0.69099144, -0.81988055,  0.79724651,  0.35932013, -0.2249909 ,
       -0.47121099, -0.89412634,  0.68298122, -0.68408791,  0.74

In [20]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.20758154  2.31970519 13.99587963 11.14117537  4.74955105  2.59101501
  1.37988638  5.23615943  3.113245    6.0426149 ]


In [21]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p])) 

[[ 1.60875558 11.93704023  0.33963409 11.22259644 11.10945718  9.09142277
   7.8858398  12.01412936  0.52071958  1.01022606]
 [ 5.21211601  7.8303124  11.10064298  9.23480219 15.31092922 11.51561362
  11.08984118  8.63328892 17.38215464 14.10952698]
 [11.7695244   0.17546445 15.34884567  4.98419704  5.28811416  6.80839879
   1.9839511   1.68077184  7.68356117  3.36898903]
 [ 3.64406987  6.73567944  4.75801617  8.62303574  6.61089598  6.7068841
   8.31431999 10.85477011  1.53411198  1.73558684]
 [ 9.68593676  3.03497832 14.77698753  9.09144657 10.09352991 11.12994068
   8.02936156  6.97900449 13.86674234  9.4710831 ]
 [11.19176836  1.01996032 15.28421283  6.45593845  6.81629353  8.34791738
   4.04086715  3.5229025   9.77257496  5.38575258]
 [ 4.9114676   5.80881406  6.58548812  5.87865082  6.77023127  3.96122715
   5.9968498   8.20253667  0.60340114  0.33261994]
 [11.14010464  0.53763769 12.30444633  3.95013864  0.75752609  2.31665224
   7.8244206   8.12094387  1.89657603  4.71431156]
 

In [22]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) 
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 2 8 7 3 3 5 8 4 0]
 [0 6 0 7 6 5 0 0 5 9]
 [1 5 1 6 0 8 6 9 6 4]
 [8 8 3 2 1 9 6 2 0 2]
 [4 2 2 1 0 7 6 4 9 0]
 [3 2 9 6 4 5 1 2 1 3]
 [4 7 2 2 1 6 5 3 7 1]
 [3 6 1 6 7 8 5 5 0 8]
 [5 4 8 1 1 3 6 7 8 0]
 [8 1 2 0 4 6 0 9 9 9]]
[[0 0 0 0 0]
 [0 7 2 8 7]
 [0 0 6 0 7]
 [0 1 5 1 6]
 [0 8 8 3 2]]


<ipython-input-22-1bb9861e61a3>:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [23]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [24]:
#82. Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


In [25]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


In [26]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix 
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 4 4]
   [1 2 0]
   [1 3 0]]

  [[4 4 1]
   [2 0 2]
   [3 0 3]]

  [[4 1 2]
   [0 2 2]
   [0 3 3]]

  [[1 2 1]
   [2 2 4]
   [3 3 1]]

  [[2 1 0]
   [2 4 3]
   [3 1 4]]

  [[1 0 4]
   [4 3 3]
   [1 4 3]]

  [[0 4 4]
   [3 3 0]
   [4 3 4]]

  [[4 4 4]
   [3 0 2]
   [3 4 4]]]


 [[[1 2 0]
   [1 3 0]
   [0 4 2]]

  [[2 0 2]
   [3 0 3]
   [4 2 3]]

  [[0 2 2]
   [0 3 3]
   [2 3 2]]

  [[2 2 4]
   [3 3 1]
   [3 2 2]]

  [[2 4 3]
   [3 1 4]
   [2 2 2]]

  [[4 3 3]
   [1 4 3]
   [2 2 3]]

  [[3 3 0]
   [4 3 4]
   [2 3 0]]

  [[3 0 2]
   [3 4 4]
   [3 0 2]]]


 [[[1 3 0]
   [0 4 2]
   [3 2 2]]

  [[3 0 3]
   [4 2 3]
   [2 2 1]]

  [[0 3 3]
   [2 3 2]
   [2 1 1]]

  [[3 3 1]
   [3 2 2]
   [1 1 2]]

  [[3 1 4]
   [2 2 2]
   [1 2 1]]

  [[1 4 3]
   [2 2 3]
   [2 1 2]]

  [[4 3 4]
   [2 3 0]
   [1 2 4]]

  [[3 4 4]
   [3 0 2]
   [2 4 1]]]


 [[[0 4 2]
   [3 2 2]
   [4 4 0]]

  [[4 2 3]
   [2 2 1]
   [4 0 2]]

  [[2 3 2]
   [2 1 1]
   [0 2 1]]

  [[3 2 2]
   [1 1 2]
   [2 1 2]]

  [[2 2 2]
   

In [27]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 1 1]
   [2 0 0]
   [3 0 0]]

  [[1 1 3]
   [0 0 1]
   [0 0 4]]

  [[1 3 0]
   [0 1 3]
   [0 4 1]]

  [[3 0 3]
   [1 3 3]
   [4 1 2]]

  [[0 3 4]
   [3 3 0]
   [1 2 3]]

  [[3 4 2]
   [3 0 1]
   [2 3 4]]

  [[4 2 1]
   [0 1 1]
   [3 4 0]]

  [[2 1 0]
   [1 1 0]
   [4 0 4]]]


 [[[2 0 0]
   [3 0 0]
   [2 4 1]]

  [[0 0 1]
   [0 0 4]
   [4 1 3]]

  [[0 1 3]
   [0 4 1]
   [1 3 2]]

  [[1 3 3]
   [4 1 2]
   [3 2 3]]

  [[3 3 0]
   [1 2 3]
   [2 3 1]]

  [[3 0 1]
   [2 3 4]
   [3 1 1]]

  [[0 1 1]
   [3 4 0]
   [1 1 3]]

  [[1 1 0]
   [4 0 4]
   [1 3 1]]]


 [[[3 0 0]
   [2 4 1]
   [2 3 1]]

  [[0 0 4]
   [4 1 3]
   [3 1 1]]

  [[0 4 1]
   [1 3 2]
   [1 1 1]]

  [[4 1 2]
   [3 2 3]
   [1 1 1]]

  [[1 2 3]
   [2 3 1]
   [1 1 4]]

  [[2 3 4]
   [3 1 1]
   [1 4 2]]

  [[3 4 0]
   [1 1 3]
   [4 2 1]]

  [[4 0 4]
   [1 3 1]
   [2 1 4]]]


 [[[2 4 1]
   [2 3 1]
   [4 0 1]]

  [[4 1 3]
   [3 1 1]
   [0 1 1]]

  [[1 3 2]
   [1 1 1]
   [1 1 4]]

  [[3 2 3]
   [1 1 1]
   [1 4 1]]

  [[2 3 1]
   

In [28]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [29]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [30]:
#88. How to implement the Game of Life using numpy arrays? 
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [31]:
#89. How to get the n largest values of an array 
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9997 9996 9998 9995]


In [32]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [34]:
#91. How to create a record array from a regular array? 
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [35]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods 
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.71 s ± 492 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
297 ms ± 53.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
277 ms ± 29.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows) 

[0 2 5]


In [39]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 1 4]
 [1 3 2]
 [4 4 2]
 [1 1 0]
 [4 2 3]
 [2 0 1]
 [4 2 0]
 [1 4 2]
 [2 4 3]
 [1 2 4]]
[[3 1 4]
 [1 3 2]
 [4 4 2]
 [1 1 0]
 [4 2 3]
 [2 0 1]
 [4 2 0]
 [1 4 2]
 [2 4 3]
 [1 2 4]]
[[3 1 4]
 [1 3 2]
 [4 4 2]
 [1 1 0]
 [4 2 3]
 [2 0 1]
 [4 2 0]
 [1 4 2]
 [2 4 3]
 [1 2 4]]


In [40]:
#95. Convert a vector of ints into a matrix binary representation 
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [43]:
#96. Given a two dimensional array, how to extract unique rows? 
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


In [44]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.02482367, 0.19923328, 0.16120956, 0.22438513, 0.10059945,
        0.2638875 , 0.11503528, 0.36931681, 0.36526301, 0.02682501],
       [0.02127136, 0.17072265, 0.1381402 , 0.19227523, 0.08620349,
        0.22612474, 0.09857353, 0.31646694, 0.31299325, 0.02298631],
       [0.02942636, 0.23617422, 0.19110033, 0.26598962, 0.11925215,
        0.31281634, 0.13636461, 0.43779389, 0.43298846, 0.03179879],
       [0.03496585, 0.28063382, 0.2270748 , 0.31606194, 0.14170126,
        0.37170375, 0.16203513, 0.52020821, 0.51449816, 0.03778488],
       [0.02524441, 0.20261016, 0.16394197, 0.22818832, 0.10230455,
        0.26836022, 0.11698506, 0.3755765 , 0.37145399, 0.02727968],
       [0.03163484, 0.2538993 , 0.20544257, 0.28595238, 0.12820213,
        0.33629348, 0.14659889, 0.4706507 , 0.46548461, 0.03418531],
       [0.00936306, 0.07514736, 0.06080547, 0.08463421, 0.03794438,
        0.09953382, 0.04338933, 0.13929995, 0.13777092, 0.01011793],
       [0.03973488, 0.3189098 , 0.2580458

In [45]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y) 

In [46]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [47]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1427282   0.23639274]
