<a href="https://colab.research.google.com/github/Lilian-Wamuhu/Lilian-Wamuhu/blob/main/Numpy_Ex_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [79]:
#How to add a border (filled with 0's) around an existing array
#step1. we create a Numpy matrix (in this case a 2x2)
array = np.ones((2, 2))
print("Original array")
print(array)


Original array
[[1. 1.]
 [1. 1.]]


In [80]:
#step2. We add the border filled with 0's to our Numpy matrix using np.pad
array = np.pad(array, pad_width=1, mode='constant',constant_values=0)
print(array)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [81]:
#What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [82]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [83]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
a = np.diag([1,2,3,4])   #simpler step
a = np.diag(1+np.arange(4),k=-1)   #advanced step
a


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [84]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
b = np.zeros((8,8),dtype=int)
b[1::2,::2] = 1
b[::2,1::2] = 1
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [85]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
c = np.unravel_index(100, (6,7,8))
c

(1, 5, 4)

In [95]:
#Create a checkerboard 8x8 matrix using the tile function
#array= np.array([[0,1], [1,0]])
d = np.tile(array,(4,4))
d

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [98]:
#Normalize a 5x5 random matrix
e = np.random.rand(5,5)
min = np.min(e)
max = np.max(e)

Norm = (e-min)/(max-min)
print(Norm)

[[0.88621927 0.57907786 0.70441116 0.31395016 0.        ]
 [0.70681074 0.7360621  0.63555444 0.41849711 0.34379466]
 [0.94371417 0.51773325 0.03479395 0.38604968 0.40017271]
 [0.88855182 0.72330201 0.79033996 0.10164547 0.37524857]
 [0.98173622 0.04400811 1.         0.56573467 0.40629959]]


In [99]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [100]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
f = np.ones((5,3))
print("first array")
print(f)
g = np.ones((3,2))
print("second array")
print(g)
z = np.dot(f,g)
print("dot product")
print(z)

first array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
second array
[[1. 1.]
 [1. 1.]
 [1. 1.]]
dot product
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [101]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.
h = np.arange(11)
h[(3 < h) & (h < 8)] *= -1
print(h)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [65]:
#What is the output of the following script? (★☆☆)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [76]:
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: ignored

In [78]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-78-7280c4eaa491>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-78-7280c4eaa491>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

In [77]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-77-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-77-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [106]:
#How to round away from zero a float array ?
y = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(y)), y))

[  6. -10.  -5.   2.   8.  -8.  -8.   3.   2.   5.]


In [107]:
#How to find common values between two arrays?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 4 8 9]
