<a href="https://colab.research.google.com/github/Lilian-Wamuhu/Lilian-Wamuhu/blob/main/Numpy_Ex_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import sys

In [39]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [ ]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
x = np.array([1,2,3,4])
y = np.array([5,6,7])
c= 1.0 / (x.reshape((-1,1)) - y)
print(c)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [ ]:
#48. Print the minimum and maximum representable value for each numpy scalar type 
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [14]:
#49. How to print all the values of an array?
x = np.arange(100)
np.set_printoptions(threshold=sys.maxsize)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [17]:
#50. How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

28


In [22]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b) 
Z= np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-22-e391db38900f>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z= np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])


In [23]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.76768944 0.25491256 0.28036819 1.00247792 0.47732715
  0.67456218 0.99552823 0.52212275 0.61319267]
 [0.76768944 0.         0.65052474 0.49882086 0.3256424  0.32153951
  0.49231473 0.24554537 0.33633051 0.33244584]
 [0.25491256 0.65052474 0.         0.18732879 0.82029485 0.32913164
  0.73371944 0.89486863 0.33773159 0.4094306 ]
 [0.28036819 0.49882086 0.18732879 0.         0.72226106 0.19695961
  0.550481   0.73651366 0.24720045 0.3432022 ]
 [1.00247792 0.3256424  0.82029485 0.72226106 0.         0.52554078
  0.81586926 0.36042743 0.48655671 0.41256062]
 [0.47732715 0.32153951 0.32913164 0.19695961 0.52554078 0.
  0.5381053  0.56646115 0.08144235 0.17483146]
 [0.67456218 0.49231473 0.73371944 0.550481   0.81586926 0.5381053
  0.         0.56824666 0.61418607 0.68465227]
 [0.99552823 0.24554537 0.89486863 0.73651366 0.36042743 0.56646115
  0.56824666 0.         0.58029108 0.56403313]
 [0.52212275 0.33633051 0.33773159 0.24720045 0.48655671 0.08144235
  0.61418607 0.580291

In [24]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

In [26]:
#54. How to read the following file?
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
#how to read it
Z = np.genfromtxt("missing.dat", delimiter=",")

In [27]:
#55. What is the equivalent of enumerate for numpy arrays?
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [28]:
#56. Generate a generic 2D Gaussian-like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [29]:
#57. How to randomly place p elements in a 2D array?
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [35]:
#58. Subtract the mean of each row of a matrix
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.04342116, -0.20785635, -0.23480242,  0.25384419, -0.14679021,
         0.04280027, -0.41054657,  0.09596885,  0.27240718,  0.37839622],
       [-0.4454182 ,  0.28909364,  0.02150822, -0.06788601,  0.06786687,
        -0.25421612, -0.29807111,  0.09180424,  0.39596057,  0.19935789],
       [ 0.04130741,  0.20983492, -0.29368595, -0.0149403 , -0.18578359,
         0.32972424, -0.43391843, -0.05272479, -0.04715264,  0.44733913],
       [-0.22573348,  0.11239871,  0.04108086, -0.0076383 , -0.09559941,
        -0.14301466,  0.29153873,  0.21519477, -0.43978821,  0.25156099],
       [ 0.20474076,  0.04873023, -0.44374975, -0.47447077,  0.08661334,
         0.33591999, -0.01715515, -0.05215497,  0.16507162,  0.1464547 ]])

In [36]:
#59. How to sort an array by the nth column?
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 7 3]
 [7 5 9]
 [6 0 7]]
[[6 0 7]
 [7 5 9]
 [9 7 3]]


In [37]:
#60. How to tell if a given 2D array has null columns? 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False
