<a href="https://colab.research.google.com/github/Lilian-Wamuhu/Lilian-Wamuhu/blob/main/Numpy_Ex_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
#Import the numpy package under the name np
import numpy as np

In [ ]:
#Print the numpy version and the configuration
print(np.__version__)
np.__config__.show()

In [ ]:
# Create a null vector of size 10
a = np.zeros(10, dtype=int)
a

In [ ]:
#How to find the memory size of any array
np.size(a)

In [ ]:
#How to get the documentation of the numpy add function from the command line? 
python -c "import numpy; numpy.info(numpy.add)"


In [ ]:
#Create a null vector of size 10 but the fifth value which is 1
z = np.zeros(10, dtype=int)
z[5] = 1
z

In [ ]:
#Create a vector with values ranging from 10 to 49
y = np.arange(10,49)
y

In [ ]:
#Reverse a vector (first element becomes last)
y[::-1]

In [63]:
#Create a 3x3 matrix with values ranging from 0 to 8
c = np.arange(0, 9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
d = np.nonzero([1,2,0,0,4,0])
d

In [ ]:
# Create a 3x3 identity matrix 
e = np.identity(3)
e

In [ ]:
#Create a 3x3x3 array with random values 
f = np.random.rand(3,3,3)
f

In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values
g = np.random.rand(10,10)
g

In [ ]:
min = np.min(g)
min

In [ ]:
max = np.max(g)
max

In [38]:
#Create a random vector of size 30 and find the mean value
h = np.random.rand(30)
mean = np.mean(h)
mean

0.4197016157176572

In [ ]:
#Create a 2d array with 1 on the border and 0 inside
i = np.ones((5,5))
i

In [ ]:
i[1:-1,1:-1]=0
i

In [ ]:
i[1:3,1:3]
i