<a href="https://colab.research.google.com/github/Lilian-Wamuhu/Lilian-Wamuhu/blob/main/Numpy_Ex_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
#31. How to ignore all numpy warnings (not recommended)?
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [ ]:
#32. Is the following expressions true? 
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-3-8b72c903599c>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [6]:
#33. How to get the dates of yesterday, today and tomorrow?
# for yesterday
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)

# for today
today = np.datetime64('today', 'D')
print("Today: ", today)
  
# for tomorrow
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)


Yesterday:  2023-02-23
Today:  2023-02-24
Tomorrow:  2023-02-25


In [7]:
#34. How to get all the dates corresponding to the month of July 2016?
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))


July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [8]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [9]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[0. 4. 7. 8. 3. 8. 1. 9. 7. 5.]
[0. 4. 7. 8. 3. 8. 1. 9. 7. 5.]
[0. 4. 7. 8. 3. 8. 1. 9. 7. 5.]
[0 4 7 8 3 8 1 9 7 5]
[0. 4. 7. 8. 3. 8. 1. 9. 7. 5.]


In [10]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [11]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [15]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [14]:
#40. Create a random vector of size 10 and sort it 
Z = np.random.rand(10)
Z = np.sort(Z)
Z

array([0.09889396, 0.25416892, 0.30811687, 0.49344944, 0.57639668,
       0.66531256, 0.67959391, 0.71384333, 0.75567416, 0.95487925])

In [16]:
#41. How to sum a small array faster than np.sum?
Z = np.arange(10)
np.add.reduce(Z)

45

In [17]:
#42. Consider two random array A and B, check if they are equal 
A = np.random.rand(0,2,5)
B = np.random.rand(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

True
True


In [19]:
#43. Make an array immutable (read-only) 
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

In [20]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[0.46252537 0.86656835 1.00492116 0.48670125 1.40749136 0.50353621
 0.97000129 0.9818281  0.91663006 0.37542864]
[0.19430064 0.31380731 0.70327673 1.44266367 0.78879769 0.74642022
 0.93009569 1.49980182 1.46282091 1.5204256 ]


In [22]:
#45. Create random vector of size 10 and replace the maximum value by 0
Z = np.random.rand(10)
Z[Z.argmax()] = 0
print(Z)

[0.59252588 0.42195981 0.19855808 0.72646085 0.         0.58040407
 0.70413126 0.32898361 0.53333012 0.14669775]
